// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC5u-jeZT4KGD_WU1HlOBO7u0Tg_2S4Kjo',
    appId: '1:443807294316:web:c6d2409e8a2d160ca9c949',
    messagingSenderId: '443807294316',
    projectId: 'turing-guard-400805',
    authDomain: 'turing-guard-400805.firebaseapp.com',
    storageBucket: 'turing-guard-400805.appspot.com',
    measurementId: 'G-R6S4YRJEHE',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFD0Q5Ewfukv1lQZbAD46-99xSWMYhr7w',
    appId: '1:443807294316:android:88b6facdf1b59937a9c949',
    messagingSenderId: '443807294316',
    projectId: 'turing-guard-400805',
    storageBucket: 'turing-guard-400805.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeS7rzxVk4XZi1dQDkRD9b95JdF0janWI',
    appId: '1:443807294316:ios:f05332ec0997d248a9c949',
    messagingSenderId: '443807294316',
    projectId: 'turing-guard-400805',
    storageBucket: 'turing-guard-400805.appspot.com',
    iosClientId: '443807294316-o51iplrt4g0jparig2osuqkgdb1i1c3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.designapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeS7rzxVk4XZi1dQDkRD9b95JdF0janWI',
    appId: '1:443807294316:ios:f05332ec0997d248a9c949',
    messagingSenderId: '443807294316',
    projectId: 'turing-guard-400805',
    storageBucket: 'turing-guard-400805.appspot.com',
    iosClientId: '443807294316-o51iplrt4g0jparig2osuqkgdb1i1c3a.apps.googleusercontent.com',
    iosBundleId: 'com.example.designapp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC5u-jeZT4KGD_WU1HlOBO7u0Tg_2S4Kjo',
    appId: '1:443807294316:web:8b7726a73facc521a9c949',
    messagingSenderId: '443807294316',
    projectId: 'turing-guard-400805',
    authDomain: 'turing-guard-400805.firebaseapp.com',
    storageBucket: 'turing-guard-400805.appspot.com',
    measurementId: 'G-BE4G2N4JG6',
  );
}
